"""empty message

Revision ID: 297059b1199d
Revises: 460789b99fd5
Create Date: 2021-09-13 11:12:42.848704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "297059b1199d"
down_revision = "460789b99fd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "study_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "study_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
