"""empty message

Revision ID: 4843080535a3
Revises: 95a6d17387c9
Create Date: 2021-07-26 15:55:23.560387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4843080535a3"
down_revision = "95a6d17387c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("start_time", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("end_time", sa.DateTime(), nullable=True)
        )
        batch_op.drop_column("timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("timestamp", sa.DATETIME(), nullable=True)
        )
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")

    # ### end Alembic commands ###
