"""empty message

Revision ID: 4c19f0b4eec5
Revises: a234d668215d
Create Date: 2021-07-22 13:49:27.757732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c19f0b4eec5"
down_revision = "a234d668215d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cfmm2tar",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("result", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cfmm2tar")),
    )
    with op.batch_alter_table("cfmm2tar", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cfmm2tar_result"), ["result"], unique=False
        )

    with op.batch_alter_table("cfm2tarr", schema=None) as batch_op:
        batch_op.drop_index("ix_cfm2tarr_result")

    op.drop_table("cfm2tarr")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cfm2tarr",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("result", sa.VARCHAR(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_cfm2tarr"),
    )
    with op.batch_alter_table("cfm2tarr", schema=None) as batch_op:
        batch_op.create_index("ix_cfm2tarr_result", ["result"], unique=False)

    with op.batch_alter_table("cfmm2tar", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cfmm2tar_result"))

    op.drop_table("cfmm2tar")
    # ### end Alembic commands ###
