"""empty message

Revision ID: 4ece0bb6663e
Revises: 46410b7eaef6
Create Date: 2023-02-24 14:27:00.840159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ece0bb6663e'
down_revision = '46410b7eaef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('dataset_hexsha', sa.Text(), nullable=False),
    sa.Column('commit_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datalad_dataset.id'], name=op.f('fk_dataset_archive_dataset_id_datalad_dataset')),
    sa.ForeignKeyConstraint(['parent_id'], ['dataset_archive.id'], name=op.f('fk_dataset_archive_parent_id_dataset_archive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_archive'))
    )
    with op.batch_alter_table('datalad_dataset', schema=None) as batch_op:
        batch_op.drop_column('archived_hexsha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datalad_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_hexsha', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('dataset_archive')
    # ### end Alembic commands ###
