"""empty message

Revision ID: 511848007f2f
Revises: eff38490649c
Create Date: 2022-04-22 09:32:00.717461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "511848007f2f"
down_revision = "eff38490649c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tar_files_in_ria", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("dataset_in_ria", sa.Boolean(), nullable=True)
        )
        batch_op.drop_column("in_ria")
    op.execute("UPDATE study SET tar_files_in_ria = false")
    op.execute("UPDATE study SET dataset_in_ria = false")
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.alter_column("tar_files_in_ria", nullable=False)
        batch_op.alter_column("dataset_in_ria", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "in_ria", sa.BOOLEAN(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("dataset_in_ria")
        batch_op.drop_column("tar_files_in_ria")

    # ### end Alembic commands ###
