"""empty message

Revision ID: 75c983055bf6
Revises: f371e0637943
Create Date: 2021-08-03 08:47:22.217053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75c983055bf6"
down_revision = "f371e0637943"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cfmm2tar", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tar_file", sa.String(length=200), nullable=True)
        )
        batch_op.add_column(
            sa.Column("uid_file", sa.String(length=200), nullable=True)
        )
        batch_op.drop_index("ix_cfmm2tar_result")
        batch_op.create_index(
            batch_op.f("ix_cfmm2tar_tar_file"), ["tar_file"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cfmm2tar_uid_file"), ["uid_file"], unique=False
        )
        batch_op.drop_column("result")

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("error", sa.String(length=128), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("error")

    with op.batch_alter_table("cfmm2tar", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("result", sa.VARCHAR(length=128), nullable=True)
        )
        batch_op.drop_index(batch_op.f("ix_cfmm2tar_uid_file"))
        batch_op.drop_index(batch_op.f("ix_cfmm2tar_tar_file"))
        batch_op.create_index("ix_cfmm2tar_result", ["result"], unique=False)
        batch_op.drop_column("uid_file")
        batch_op.drop_column("tar_file")

    # ### end Alembic commands ###
