"""empty message

Revision ID: a234d668215d
Revises: a11fc23f71bf
Create Date: 2021-07-22 12:44:33.588677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a234d668215d"
down_revision = "a11fc23f71bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cfm2tarr",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("result", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cfm2tarr")),
    )
    with op.batch_alter_table("cfm2tarr", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cfm2tarr_result"), ["result"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_pressed_button_id", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_pressed_button_id")

    with op.batch_alter_table("cfm2tarr", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cfm2tarr_result"))

    op.drop_table("cfm2tarr")
    # ### end Alembic commands ###
