"""empty message

Revision ID: e05acc4b754d
Revises: be4aea182c3a
Create Date: 2022-04-20 14:45:35.821968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e05acc4b754d"
down_revision = "be4aea182c3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(sa.Column("in_ria", sa.Boolean(), nullable=True))
    op.execute("UPDATE study SET in_ria = false")
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.alter_column("in_ria", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("in_ria")

    # ### end Alembic commands ###
