"""empty message

Revision ID: f371e0637943
Revises: 4843080535a3
Create Date: 2021-07-27 12:25:09.197207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f371e0637943"
down_revision = "4843080535a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("task_button_id", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("task_button_id")

    # ### end Alembic commands ###
