"""empty message

Revision ID: f48a768460d1
Revises: c24527268a79
Create Date: 2022-03-30 10:35:06.371933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f48a768460d1"
down_revision = "c24527268a79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("explicit_patient", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("patient_name", sa.String(length=194), nullable=True)
        )
        batch_op.add_column(
            sa.Column("dicom_study_id", sa.String(length=16), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("explicit_patient", schema=None) as batch_op:
        batch_op.drop_column("dicom_study_id")
        batch_op.drop_column("patient_name")

    # ### end Alembic commands ###
