"""empty message

Revision ID: f7a3b9b04159
Revises: 96ab962880b5
Create Date: 2022-06-03 09:52:10.374744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7a3b9b04159"
down_revision = "96ab962880b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=True))
    op.execute("UPDATE study SET active = false")
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.alter_column("active", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
