services:
  autobidsportal:
    build: &idautobidsbuild
      context: .
      dockerfile: Dockerfile-production
    env_file: &idautobidsenv .env
    ports: ["5000:5000"]
    volumes: &idautobidsvolumes
      - "/home/debian/mnt/cfmm2tar-tmp:/cfmm2tar-download"
      - "/home/debian/mnt/tar2bids-tmp:/tar-files"
      - "/home/debian/opt/autobidsapp/datasets:/datasets"
      - "/home/debian/opt/autobidsapp/appdata:/appdata"
      - "/home/debian/.ssh:/ssh"
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    privileged: true
    depends_on:
      - postgres
      - redis
      - rq
    logging: &idautobidslog
      driver: "json-file"
      options:
        max-size: "300k" # Maximum 300kB file
        max-file: "10" # Rotate between a max of 10 log files

  rq:
    build: *idautobidsbuild
    command: rq worker
    env_file: *idautobidsenv
    volumes: *idautobidsvolumes
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    privileged: true
    depends_on:
      - postgres
      - redis
    restart: on-failure
    logging: *idautobidslog

  redis:
    image: redis:5.0.14
    environment:
      TZ: "America/Toronto"
    ports: ["6379:6379"]
    logging: *idautobidslog

  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: UPDATEME
      TZ: "America/Toronto"
    volumes:
      - "/home/debian/opt/autobidsapp/postgres-db:/var/lib/postgresql/data"
    ports: ["5432:5432"]
    logging: *idautobidslog

  nginx:
    image: nginx:latest
    hostname: nginx
    environment:
      TZ: "America/Toronto"
    volumes:
      - "./compose/nginx.conf:/etc/nginx/nginx.conf"
    ports: ["5001:80"]
    depends_on:
      - autobidsportal
    logging: *idautobidslog
