"""Add new column and remove old column

Revision ID: 00e716e0268d
Revises: ef4591842f3e
Create Date: 2021-05-12 13:21:50.177884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e716e0268d'
down_revision = 'ef4591842f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_answer_submission_date'), ['submission_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_submission_date'))
        batch_op.drop_column('submission_date')

    # ### end Alembic commands ###
