"""empty message

Revision ID: 01c660ea1a21
Revises: 75c983055bf6
Create Date: 2021-08-05 09:20:08.349726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c660ea1a21'
down_revision = '75c983055bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfmm2tar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_button_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfmm2tar', schema=None) as batch_op:
        batch_op.drop_column('task_button_id')

    # ### end Alembic commands ###
