"""empty message

Revision ID: 08452086edec
Revises: b3e7c7e596da
Create Date: 2021-05-07 11:00:59.644029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08452086edec'
down_revision = 'b3e7c7e596da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    # ### end Alembic commands ###
