"""empty message

Revision ID: 0ac2c5dd957c
Revises: b771ad758302
Create Date: 2022-03-25 13:35:59.183031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ac2c5dd957c"
down_revision = "b771ad758302"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "explicit_patient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("study_instance_uid", sa.String(length=64), nullable=True),
        sa.Column("included", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["study.id"],
            name=op.f("fk_explicit_patient_study_id_study"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_explicit_patient")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("explicit_patient")
    # ### end Alembic commands ###
