"""empty message

Revision ID: 0f2dfb1701f7
Revises: be4aea182c3a
Create Date: 2022-04-01 14:11:25.690361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f2dfb1701f7"
down_revision = "be4aea182c3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tar2bids_img",
                sa.Text(),
                nullable=True,
                server_default="khanlab_tar2bids_v0.0.6.sif",
            )
        )
        batch_op.alter_column("tar2bids_img", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("tar2bids_img")

    # ### end Alembic commands ###
