"""empty message

Revision ID: 15b10ad3cee8
Revises: cd1bb82fd708
Create Date: 2021-08-13 11:25:18.419529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b10ad3cee8'
down_revision = 'cd1bb82fd708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_heuristic', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('other_heuristic')

    # ### end Alembic commands ###
