"""Add sample column

Revision ID: 1b41d17ee9fd
Revises: f9db4720f5f4
Create Date: 2021-05-14 15:19:37.111561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b41d17ee9fd'
down_revision = 'f9db4720f5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('sample')

    # ### end Alembic commands ###
