"""empty message

Revision ID: 2a2cbf8f836b
Revises: e22f2179c1be
Create Date: 2022-03-28 13:44:02.907943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a2cbf8f836b"
down_revision = "e22f2179c1be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.alter_column(
            "sample", existing_type=sa.DATETIME(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.alter_column(
            "sample", existing_type=sa.DATETIME(), nullable=False
        )

    # ### end Alembic commands ###
