"""Resolve error

Revision ID: 35266d9fc923
Revises: 239659cf00e8
Create Date: 2021-05-11 10:43:26.116410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35266d9fc923'
down_revision = '239659cf00e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_submitter_id_submitter'), 'submitter', ['submitter_id'], ['id'])
        batch_op.drop_column('name_input')
        batch_op.drop_column('email_input')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('email_input', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('name_input', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_answer_submitter_id_submitter'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
