"""empty message

Revision ID: 384fe72e3812
Revises: e125f6d12440
Create Date: 2021-08-19 16:46:40.756815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384fe72e3812'
down_revision = 'e125f6d12440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choice'))
    )
    op.drop_table('choices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_choices')
    )
    op.drop_table('choice')
    # ### end Alembic commands ###
