# Newest
"""empty message

Revision ID: 3a8ccc756127
Revises: 60b071af63d5
Create Date: 2021-05-07 13:43:59.744336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8ccc756127'
down_revision = '60b071af63d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts') as batch_op:
        batch_op.drop_column('tags')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'submitter', ['submitter_id'], ['id'])
    op.drop_column('answer', 'email_input')
    op.drop_column('answer', 'user_id')
    op.drop_column('answer', 'name_input')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('answer', sa.Column('name_input', sa.VARCHAR(length=20), nullable=True))
    op.add_column('answer', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('answer', sa.Column('email_input', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
