"""Provide default heuristic and subj_expr

Revision ID: 460789b99fd5
Revises: 57d0a5f7aa51
Create Date: 2021-09-13 10:52:19.698827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "460789b99fd5"
down_revision = "57d0a5f7aa51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.alter_column(
            "heuristic", existing_type=sa.VARCHAR(length=200), nullable=False
        )
        batch_op.alter_column(
            "subj_expr", existing_type=sa.VARCHAR(length=50), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.alter_column(
            "subj_expr", existing_type=sa.VARCHAR(length=50), nullable=True
        )
        batch_op.alter_column(
            "heuristic", existing_type=sa.VARCHAR(length=200), nullable=True
        )

    # ### end Alembic commands ###
