"""Make Task.user nullable

Revision ID: 4e12d841fcc8
Revises: a1e0cc012a6d
Create Date: 2021-10-13 10:21:42.680083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e12d841fcc8"
down_revision = "a1e0cc012a6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
