"""empty message

Revision ID: 57d0a5f7aa51
Revises: 61572ff9ea0b
Create Date: 2021-09-03 12:02:29.722046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57d0a5f7aa51"
down_revision = "61572ff9ea0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("subj_expr", sa.String(length=50), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("subj_expr")

    # ### end Alembic commands ###
