"""empty message

Revision ID: 59c756d48de4
Revises: f571faa7a69b
Create Date: 2021-05-07 10:04:25.958691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c756d48de4'
down_revision = 'f571faa7a69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('email_input', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('name_input', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'name_input')
    op.drop_column('answer', 'email_input')
    # ### end Alembic commands ###
