"""empty message

Revision ID: 5b823749a511
Revises: bedbdb9aae3c
Create Date: 2021-07-26 14:30:00.872250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b823749a511"
down_revision = "bedbdb9aae3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cfmm2tar", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_cfmm2tar_user_id_user"), "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cfmm2tar", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_cfmm2tar_user_id_user"), type_="foreignkey"
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
