"""add new columns

Revision ID: 60b071af63d5
Revises: 08452086edec
Create Date: 2021-05-07 13:00:02.338508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b071af63d5'
down_revision = '08452086edec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answer', sa.Column('submitter_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'submitter', ['submitter_id'], ['id'])
    op.drop_column('answer', 'name_input')
    op.drop_column('answer', 'email_input')
    op.drop_column('answer', 'user_id')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('answer', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('answer', sa.Column('email_input', sa.VARCHAR(length=20), nullable=True))
    op.add_column('answer', sa.Column('name_input', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'])
    op.drop_column('answer', 'submitter_id')
    op.drop_table('submitter')
    # ### end Alembic commands ###
