"""Refactor all models

Revision ID: 61572ff9ea0b
Revises: bef4990c0b7d
Create Date: 2021-08-30 15:23:12.157765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61572ff9ea0b'
down_revision = 'bef4990c0b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_name', sa.String(length=100), nullable=False),
    sa.Column('submitter_email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scanner', sa.String(length=20), nullable=False),
    sa.Column('scan_number', sa.Integer(), nullable=False),
    sa.Column('study_type', sa.Boolean(), nullable=False),
    sa.Column('familiarity_bids', sa.String(length=20), nullable=False),
    sa.Column('familiarity_bidsapp', sa.String(length=20), nullable=False),
    sa.Column('familiarity_python', sa.String(length=20), nullable=False),
    sa.Column('familiarity_linux', sa.String(length=20), nullable=False),
    sa.Column('familiarity_bash', sa.String(length=20), nullable=False),
    sa.Column('familiarity_hpc', sa.String(length=20), nullable=False),
    sa.Column('familiarity_openneuro', sa.String(length=20), nullable=False),
    sa.Column('familiarity_cbrain', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.String(length=20), nullable=False),
    sa.Column('project_name', sa.String(length=20), nullable=False),
    sa.Column('dataset_name', sa.String(length=20), nullable=False),
    sa.Column('sample', sa.DateTime(), nullable=False),
    sa.Column('retrospective_data', sa.Boolean(), nullable=False),
    sa.Column('retrospective_start', sa.DateTime(), nullable=True),
    sa.Column('retrospective_end', sa.DateTime(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('heuristic', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study'))
    )
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_submission_date'), ['submission_date'], unique=False)

    op.create_table('accessible_studies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('fk_accessible_studies_study_id_study')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_accessible_studies_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'study_id', name=op.f('pk_accessible_studies'))
    )
    op.create_table('cfmm2tar_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('tar_file', sa.String(length=200), nullable=False),
    sa.Column('uid', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('fk_cfmm2tar_output_study_id_study')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cfmm2tar_output'))
    )
    with op.batch_alter_table('cfmm2tar_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfmm2tar_output_tar_file'), ['tar_file'], unique=False)
        batch_op.create_index(batch_op.f('ix_cfmm2tar_output_uid'), ['uid'], unique=False)

    op.create_table('tar2bids_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('bids_dir', sa.String(length=200), nullable=True),
    sa.Column('heuristic', sa.String(length=200), nullable=True),
    sa.Column('cfmm2tar_output_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cfmm2tar_output_id'], ['cfmm2tar_output.id'], name=op.f('fk_tar2bids_output_cfmm2tar_output_id_cfmm2tar_output')),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('fk_tar2bids_output_study_id_study')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tar2bids_output'))
    )
    with op.batch_alter_table('tar2bids_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tar2bids_output_bids_dir'), ['bids_dir'], unique=False)
        batch_op.create_index(batch_op.f('ix_tar2bids_output_heuristic'), ['heuristic'], unique=False)

    op.drop_table('choice')
    with op.batch_alter_table('cfmm2tar', schema=None) as batch_op:
        batch_op.drop_index('ix_cfmm2tar_tar_file')
        batch_op.drop_index('ix_cfmm2tar_uid_file')

    op.drop_table('cfmm2tar')
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index('ix_answer_submission_date')

    op.drop_table('answer')
    op.drop_table('user_choices')
    op.drop_table('submitter')
    with op.batch_alter_table('tar2bids', schema=None) as batch_op:
        batch_op.drop_index('ix_tar2bids_bids_file')
        batch_op.drop_index('ix_tar2bids_heuristic')
        batch_op.drop_index('ix_tar2bids_tar_file')

    op.drop_table('tar2bids')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('payload_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_id', sa.Integer(), nullable=False))
        batch_op.alter_column('complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_task_study_id_study'), 'study', ['study_id'], ['id'])
        batch_op.drop_column('task_button_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('last_pressed_button_id')
        batch_op.drop_column('selected_heuristic')
        batch_op.drop_column('other_heuristic')
        batch_op.drop_column('second_last_pressed_button_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_last_pressed_button_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('other_heuristic', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('selected_heuristic', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('last_pressed_button_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_button_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_task_study_id_study'), type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('study_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('payload_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    op.create_table('tar2bids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('task_button_id', sa.INTEGER(), nullable=True),
    sa.Column('tar_file_id', sa.INTEGER(), nullable=True),
    sa.Column('bids_file', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tar_file', sa.VARCHAR(length=200), nullable=True),
    sa.Column('heuristic', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_tar2bids_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_tar2bids')
    )
    with op.batch_alter_table('tar2bids', schema=None) as batch_op:
        batch_op.create_index('ix_tar2bids_tar_file', ['tar_file'], unique=False)
        batch_op.create_index('ix_tar2bids_heuristic', ['heuristic'], unique=False)
        batch_op.create_index('ix_tar2bids_bids_file', ['bids_file'], unique=False)

    op.create_table('submitter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_submitter')
    )
    op.create_table('user_choices',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('choice_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['choice.id'], name='fk_user_choices_choice_id_choice'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_choices_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'choice_id', name='pk_user_choices')
    )
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('scanner', sa.VARCHAR(length=20), nullable=True),
    sa.Column('scan_number', sa.INTEGER(), nullable=True),
    sa.Column('study_type', sa.BOOLEAN(), nullable=True),
    sa.Column('familiarity_bids', sa.VARCHAR(length=20), nullable=True),
    sa.Column('familiarity_bidsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('familiarity_python', sa.VARCHAR(length=20), nullable=True),
    sa.Column('familiarity_linux', sa.VARCHAR(length=20), nullable=True),
    sa.Column('familiarity_bash', sa.VARCHAR(length=20), nullable=True),
    sa.Column('familiarity_hpc', sa.VARCHAR(length=20), nullable=True),
    sa.Column('familiarity_openneuro', sa.VARCHAR(length=20), nullable=True),
    sa.Column('familiarity_cbrain', sa.VARCHAR(length=20), nullable=True),
    sa.Column('principal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('principal_other', sa.VARCHAR(length=20), nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dataset_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sample', sa.DATETIME(), nullable=True),
    sa.Column('retrospective_data', sa.BOOLEAN(), nullable=True),
    sa.Column('retrospective_start', sa.DATETIME(), nullable=True),
    sa.Column('retrospective_end', sa.DATETIME(), nullable=True),
    sa.Column('consent', sa.BOOLEAN(), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=200), nullable=True),
    sa.Column('submission_date', sa.DATETIME(), nullable=True),
    sa.Column('submitter_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['submitter.id'], name='fk_answer_submitter_id_submitter'),
    sa.PrimaryKeyConstraint('id', name='pk_answer')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index('ix_answer_submission_date', ['submission_date'], unique=False)

    op.create_table('cfmm2tar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('tar_file', sa.VARCHAR(length=200), nullable=True),
    sa.Column('uid_file', sa.VARCHAR(length=200), nullable=True),
    sa.Column('task_button_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_cfmm2tar_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_cfmm2tar')
    )
    with op.batch_alter_table('cfmm2tar', schema=None) as batch_op:
        batch_op.create_index('ix_cfmm2tar_uid_file', ['uid_file'], unique=False)
        batch_op.create_index('ix_cfmm2tar_tar_file', ['tar_file'], unique=False)

    op.create_table('choice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_choice')
    )
    with op.batch_alter_table('tar2bids_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tar2bids_output_heuristic'))
        batch_op.drop_index(batch_op.f('ix_tar2bids_output_bids_dir'))

    op.drop_table('tar2bids_output')
    with op.batch_alter_table('cfmm2tar_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfmm2tar_output_uid'))
        batch_op.drop_index(batch_op.f('ix_cfmm2tar_output_tar_file'))

    op.drop_table('cfmm2tar_output')
    op.drop_table('accessible_studies')
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_submission_date'))

    op.drop_table('study')
    # ### end Alembic commands ###
