"""empty message

Revision ID: 6444e0280948
Revises: f188678f89e9
Create Date: 2021-06-25 11:20:32.907124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6444e0280948'
down_revision = 'f188678f89e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_other', sa.String(length=20), nullable=True))
        batch_op.drop_column('prinicpal_other')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prinicpal_other', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('principal_other')

    # ### end Alembic commands ###
