"""empty message

Revision ID: 93153139b036
Revises: 5ca67c235af0
Create Date: 2022-11-08 14:06:43.089063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93153139b036"
down_revision = "5ca67c235af0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("custom_bidsignore", sa.Text(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("custom_bidsignore")

    # ### end Alembic commands ###
