"""empty message

Revision ID: 95a6d17387c9
Revises: 45de2fe4035d
Create Date: 2021-07-26 15:30:41.498671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95a6d17387c9"
down_revision = "45de2fe4035d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.FLOAT(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.drop_index("ix_task_timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index("ix_task_timestamp", ["timestamp"], unique=False)
        batch_op.alter_column(
            "timestamp",
            existing_type=sa.DateTime(),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
