"""empty message

Revision ID: 970a0420bce9
Revises: 36e9f11fe475
Create Date: 2022-05-17 14:43:49.271069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970a0420bce9'
down_revision = '36e9f11fe475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datalad_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_hexsha', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datalad_dataset', schema=None) as batch_op:
        batch_op.drop_column('archived_hexsha')

    # ### end Alembic commands ###
