"""add patient_str

Revision ID: a1e0cc012a6d
Revises: 297059b1199d
Create Date: 2021-09-22 15:22:02.397835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1e0cc012a6d"
down_revision = "297059b1199d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("patient_str", sa.String(length=50), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("patient_str")
    # ### end Alembic commands ###
