"""Latest version

Revision ID: aa7395283d06
Revises: 04b27f747b69
Create Date: 2021-05-10 10:21:35.960464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7395283d06'
down_revision = '04b27f747b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('familiarity_bash', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('familiarity_bids', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('familiarity_bidsapp', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('familiarity_cbrain', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('familiarity_hpc', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('familiarity_linux', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('familiarity_openneuro', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('familiarity_python', sa.String(length=20), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'submitter', ['submitter_id'], ['id'])
    op.drop_column('answer', 'user_id')
    op.drop_column('answer', 'name_input')
    op.drop_column('answer', 'email_input')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('answer', sa.Column('email_input', sa.VARCHAR(length=20), nullable=True))
    op.add_column('answer', sa.Column('name_input', sa.VARCHAR(length=20), nullable=True))
    op.add_column('answer', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'])
    op.drop_column('answer', 'familiarity_python')
    op.drop_column('answer', 'familiarity_openneuro')
    op.drop_column('answer', 'familiarity_linux')
    op.drop_column('answer', 'familiarity_hpc')
    op.drop_column('answer', 'familiarity_cbrain')
    op.drop_column('answer', 'familiarity_bidsapp')
    op.drop_column('answer', 'familiarity_bids')
    op.drop_column('answer', 'familiarity_bash')
    # ### end Alembic commands ###
