"""empty message

Revision ID: b3e7c7e596da
Revises: 59c756d48de4
Create Date: 2021-05-07 10:17:54.435886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e7c7e596da'
down_revision = '59c756d48de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('email_input', sa.String(length=20), nullable=True))
    op.add_column('answer', sa.Column('name_input', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'name_input')
    op.drop_column('answer', 'email_input')
    # ### end Alembic commands ###
