"""empty message

Revision ID: be4aea182c3a
Revises: f48a768460d1
Create Date: 2022-03-30 13:39:26.717260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be4aea182c3a"
down_revision = "f48a768460d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("explicit_patient", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_explicit_patient_study_instance_uid"),
            ["study_instance_uid"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("explicit_patient", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_explicit_patient_study_instance_uid"),
            type_="unique",
        )

    # ### end Alembic commands ###
