"""empty message

Revision ID: bef4990c0b7d
Revises: 720ca7347aaa
Create Date: 2021-08-20 09:23:37.041144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bef4990c0b7d"
down_revision = "720ca7347aaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_choices",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("choice_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["choice_id"],
            ["choice.id"],
            name=op.f("fk_user_choices_choice_id_choice"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_choices_user_id_user")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "choice_id", name=op.f("pk_user_choices")
        ),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("access_to")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("access_to", sa.VARCHAR(length=128), nullable=True)
        )

    op.drop_table("user_choices")
    # ### end Alembic commands ###
