"""empty message

Revision ID: c24527268a79
Revises: 2a2cbf8f836b
Create Date: 2022-03-29 13:17:45.722843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24527268a79'
down_revision = '2a2cbf8f836b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explicit_patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=64), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('fk_explicit_patient_study_id_study')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explicit_patient'))
    )
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name_re', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('patient_name_re')

    op.drop_table('explicit_patient')
    # ### end Alembic commands ###
