"""empty message

Revision ID: c4fdde0cd53d
Revises: 93153139b036
Create Date: 2022-11-23 09:54:20.817679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c4fdde0cd53d"
down_revision = "93153139b036"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "deface", sa.Boolean(), nullable=False, server_default="false"
            )
        )
        batch_op.alter_column("deface", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("deface")

    # ### end Alembic commands ###
