"""User, Answer, Submitter and Principal tables

Revision ID: c7955becca6e
Revises: 
Create Date: 2021-07-15 14:36:03.399585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7955becca6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_principal'))
    )
    op.create_table('submitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submitter'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scanner', sa.String(length=20), nullable=True),
    sa.Column('scan_number', sa.Integer(), nullable=True),
    sa.Column('study_type', sa.Boolean(), nullable=True),
    sa.Column('familiarity_bids', sa.String(length=20), nullable=True),
    sa.Column('familiarity_bidsapp', sa.String(length=20), nullable=True),
    sa.Column('familiarity_python', sa.String(length=20), nullable=True),
    sa.Column('familiarity_linux', sa.String(length=20), nullable=True),
    sa.Column('familiarity_bash', sa.String(length=20), nullable=True),
    sa.Column('familiarity_hpc', sa.String(length=20), nullable=True),
    sa.Column('familiarity_openneuro', sa.String(length=20), nullable=True),
    sa.Column('familiarity_cbrain', sa.String(length=20), nullable=True),
    sa.Column('principal', sa.String(length=20), nullable=True),
    sa.Column('principal_other', sa.String(length=20), nullable=True),
    sa.Column('project_name', sa.String(length=20), nullable=True),
    sa.Column('dataset_name', sa.String(length=20), nullable=True),
    sa.Column('sample', sa.DateTime(), nullable=True),
    sa.Column('retrospective_data', sa.Boolean(), nullable=True),
    sa.Column('retrospective_start', sa.DateTime(), nullable=True),
    sa.Column('retrospective_end', sa.DateTime(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['submitter.id'], name=op.f('fk_answer_submitter_id_submitter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer'))
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_submission_date'), ['submission_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_submission_date'))

    op.drop_table('answer')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('submitter')
    op.drop_table('principal')
    # ### end Alembic commands ###
