"""empty message

Revision ID: dbec821937c6
Revises: ccb400cdf89d
Create Date: 2021-08-12 10:25:56.493991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbec821937c6"
down_revision = "ccb400cdf89d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tar2bids", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tar_file", sa.String(length=200), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_tar2bids_tar_file"), ["tar_file"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tar2bids", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tar2bids_tar_file"))
        batch_op.drop_column("tar_file")

    # ### end Alembic commands ###
