"""empty message

Revision ID: dc8467270eaf
Revises: 6d5545547b89
Create Date: 2022-05-06 13:46:57.521531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8467270eaf'
down_revision = '6d5545547b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datalad_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_ria_url', sa.Text(), nullable=True))

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_ria_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('custom_ria_url')

    with op.batch_alter_table('datalad_dataset', schema=None) as batch_op:
        batch_op.drop_column('custom_ria_url')

    # ### end Alembic commands ###
