"""empty message

Revision ID: eff38490649c
Revises: e05acc4b754d
Create Date: 2022-04-21 10:06:46.703958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eff38490649c"
down_revision = "e05acc4b754d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("dataset_content", sa.JSON(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study", schema=None) as batch_op:
        batch_op.drop_column("dataset_content")

    # ### end Alembic commands ###
