"""Remove unused columns

Revision ID: f9db4720f5f4
Revises: e4fd8a1d6cf9
Create Date: 2021-05-13 11:17:49.898539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9db4720f5f4'
down_revision = 'e4fd8a1d6cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('familiarity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familiarity', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
